name: VLensDemoApp
options:
  bundleIdPrefix: com.vlens
  deploymentTarget:
    iOS: "15.0"

packages:
  VLensLib:
    path: ../

targets:
  VLensDemoApp:
    type: application
    platform: iOS
    sources:
      - VLensDemoApp
    entitlements:
      path: VLensDemoApp/VLensDemoApp.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vlens.vlensIOSDemo
        INFOPLIST_FILE: VLensDemoApp/Resources/Info.plist
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    dependencies:
      - package: VLensLib
